name: example
description: "A sample app for markdown widgets."
publish_to: 'none'
version: 0.0.4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  path_provider: ^2.1.5
  markdown_widget_builder: # ^0.0.4
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

dependency_overrides:
  flutter_secure_storage_linux: ^2.0.1
  flutter_secure_storage_platform_interface: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/surveys/
    - assets/surveys/media/
